name: drug_safety_warehouse
version: "1.0.0"

profile: drug_safety_warehouse

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets: ["target", "dbt_packages"]

models:
    drug_safety_warehouse:
        staging:
            +materialized: view
        intermediate:
            +materialized: view
        marts:
            +materialized: table

seeds:
    drug_safety_warehouse:
        +quote_columns: false
        faers_outcome_codes:
            +column_types:
                outcome_code: string
                outcome_label: string

